before:
  hooks:
    - go mod tidy
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      386: i386
checksum:
  name_template: 'checksums.txt'
